# Spring Cloud Gateway Configuration
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enable: true
              lower-case-service-id: true
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
