# Spring Cloud Gateway Configuration
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

springdoc:
  swagger-ui:
    urls:
      - name: keynote-service
        url: /keynote-service/v3/api-docs
      - name: conference-service
        url: /conference-service/v3/api-docs
      - name: analytics-service
        url: /analytics-service/v3/api-docs
  api-docs:
    enabled: true
